spring.application.name=clubee

# Banco de dados
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# OBS.: spring.sql.init.mode=always em desenvolvimento com scripts .sql no classpath. Em produção, normalmente é never.

# JWT config
jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

# OBS.: Isso está prejudicando a segurança da aplicação.

# E-mail config
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

# RabbitMQ config
spring.rabbitmq.addresses=
spring.rabbitmq.ssl.enabled=
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=100
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2

# RabbitMQ exchanges
email.exchange.name=

# RabbitMQ queues
email.password.queue.name=

# RabbitMQ routing-keys
email.password.routing.key=

# Swagger config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/v3/api-docs
springdoc.swagger-ui.url=/openapi.yaml
